model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_base: https://openai-azure-endpoint.openai.azure.com
      api_key: os.environ/AZURE_API_KEY
      api_version: "2024-02-15-preview"
  
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  
router_settings:
  routing_strategy: "simple-shuffle"
  model_group_alias: {"gpt-4": "gpt-3.5-turbo"}
  num_retries: 2
  timeout: 600
  
litellm_settings:
  drop_params: true
  set_verbose: false