name: Test AWS Credentials

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Test AWS CLI
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity
          echo "✅ AWS credentials are working!"
      
      - name: List CloudFormation Stacks
        run: |
          echo "Listing existing CloudFormation stacks..."
          aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query 'StackSummaries[?contains(StackName, `LiteLLM`)].StackName' --output table || true